backup:
	cp -r ~/.config/sublime-text-3/Packages/User .

restore:
	mv ~/.config/sublime-text-3/Packages/User \
	   ~/.config/sublime-text-3/Packages/User.old
	cp -r User ~/.config/sublime-text-3/Packages

.PHONY: *
