FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

# create working directory
RUN mkdir -p /src
WORKDIR /src

# install essentials and dependencies
COPY apt-system-requirements.txt /src
RUN apt-get update && \
    apt-get install -y --no-install-recommends $(cat apt-system-requirements.txt) && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install project dependencies
COPY requirements.txt /src
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
